config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :travel_maps do
      member do
      post :remove
    end
  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'
  resources :home do
    collection do
      post :search
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :travel_maps
  
  extend FriendlyId
  friendly_id :first_name, use: :slugged
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    # @locations = current_user.profile.travel_maps.first.locations
    
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to root_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :street, :suburb, :postcode, :state, :country, :phone, :photo, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :street %>
    <%= f.input :suburb %>
    <%= f.input :postcode %>
    <%= f.input :state %>
    <%= f.input :country %>
    <%= f.input :phone %>
    <%= f.input :photo %>
  <!--  <%= f.association :user %>-->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country</th>
      <th>Phone</th>
      <th>Photo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.street %></td>
        <td><%= profile.suburb %></td>
        <td><%= profile.postcode %></td>
        <td><%= profile.state %></td>
        <td><%= profile.country %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.photo %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class = "row">
  <div class = "col-md-3">
    <div class = "panel panel-default">
      <div class = "panel-body">
        
        <div class = "text-center">
        <%= fa_icon "user 5x" %>
        <h2>
          <%= @profile.first_name %>
        </h2>
        <p>
          <%= link_to 'Edit Profile', edit_profile_path(@profile) %>
        </p>
        </div>

        <% if not current_user %>
          <p>
            <strong>Street:</strong>
            <%= @profile.street %>
          </p>
          
          <p>
            <strong>Suburb:</strong>
            <%= @profile.suburb %>
          </p>
          
          <p>
            <strong>Postcode:</strong>
            <%= @profile.postcode %>
          </p>
          
          <p>
            <strong>State:</strong>
            <%= @profile.state %>
          </p>
          
          <p>
            <strong>Country:</strong>
            <%= @profile.country %>
          </p>
          
          <p>
            <strong>Phone:</strong>
            <%= @profile.phone %>
          </p>
          
        <% end %>
      </div>
    </div>
  </div>
  
  
  <div class = "col-md-9">
    <div class = "panel panel-default">

      <div class = "panel-heading">
        <h4>My Adventures</h4>  
      </div>

      <div class = "panel-body">

        <div class = "row">
          
          <% @profile.travel_maps.each do |travel_map| %>
            <div class = "col-md-12">
              <div class = "panel panel-default">
                <div class = "panel-body">

                  <%= link_to travel_map_path(travel_map), style: "color: black;"  do %>
                        <div class="row">
                          <div class="col-md-2 text-center">
                              <%= fa_icon "map-o 3x" %>
                          </div>
                          <div class="col-md-4">
                            <p><%= travel_map.name %></p>
                          </div>
                          <div class="col-md-6">
                            <p><%= travel_map.description %></p>
                          </div>
                        </div>
                  <% end %>
            
                </div>
              </div>
            </div>
          
          <% end %>
          
        </div>
      </div>

      <div class="panel-footer">  
      <%= link_to "Add a new adventure", new_travel_map_path %>
      </div>

    </div>
  </div>
  
</div>

<p id="notice"><%= notice %></p>