config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :travel_maps do
      member do
      post :remove
    end
  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'
  resources :home do
    collection do
      post :search
    end
  end

end

app/models/travel_map.rb
class TravelMap < ActiveRecord::Base
  belongs_to :profile
  has_many :travel_map_locations
  has_many :locations, through: :travel_map_locations
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
end

app/controllers/travel_maps_controller.rb
class TravelMapsController < ApplicationController
  before_action :set_travel_map, only: [:show, :edit, :update, :destroy, :remove]

  # GET /travel_maps
  # GET /travel_maps.json
  def index
    @travel_maps = TravelMap.all
  end

  # GET /travel_maps/1
  # GET /travel_maps/1.json
  def show

    @locations = @travel_map.locations

    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end
    
    @shortest_travel_time = ""
    
    if @locations.count < 5
      
      @comb_locations = @locations.combination(2).to_a
      
      @comb_locations.each do |location|
        
        puts location
        latlng_origin = location[0].latitude.to_s + "," + location[0].longitude.to_s
        latlng_destination = location[1].latitude.to_s + "," + location[1].longitude.to_s
        google_initialise = GoogleMap.new(latlng_origin, latlng_destination)
        directions = google_initialise.directions
        puts directions
        body = JSON.parse(directions.body)
        puts body
        
        if body["status"] == "ZERO_RESULTS"
        else
          distance = body["routes"][0]["legs"][0]["distance"]["value"]
        end
      end
      
    end

  end

  # GET /travel_maps/new
  def new
    @travel_map = TravelMap.new
  end

  # GET /travel_maps/1/edit
  def edit
  end

  def remove
    @location = @travel_map.locations.find(params[:location])
    @travel_map.locations.delete(@location)

    respond_to do |format|
      format.html { redirect_to @travel_map, notice: 'Location was succesfully removed.' }
      format.json { render :show, status: :created, location: @travel_map } 
    end
  end

  # POST /travel_maps
  # POST /travel_maps.json
  def create
    @travel_map = TravelMap.new(travel_map_params)
    @travel_map.profile = current_user.profile

    respond_to do |format|
      if @travel_map.save
        format.html { redirect_to @travel_map, notice: 'Travel map was successfully created.' }
        format.json { render :show, status: :created, location: @travel_map }
      else
        format.html { render :new }
        format.json { render json: @travel_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /travel_maps/1
  # PATCH/PUT /travel_maps/1.json
  def update
    respond_to do |format|
      if @travel_map.update(travel_map_params)
        format.html { redirect_to @travel_map, notice: 'Travel map was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel_map }
      else
        format.html { render :edit }
        format.json { render json: @travel_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travel_maps/1
  # DELETE /travel_maps/1.json
  def destroy
    @travel_map.destroy
    respond_to do |format|
      format.html { redirect_to travel_maps_url, notice: 'Travel map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel_map
      @travel_map = TravelMap.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_map_params
      params.require(:travel_map).permit(:name, :description, :duration, :cost, :profile_id)
    end
end

app/helpers/travel_maps_helper.rb
module TravelMapsHelper
end

app/views/travel_maps/_form.html.erb
<%= simple_form_for(@travel_map) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
     <!--f.input :duration-->
     <!--f.input :cost-->
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/travel_maps/edit.html.erb
<h1>Editing Travel Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @travel_map %> |
<%= link_to 'Back', travel_maps_path %>

app/views/travel_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Travel Maps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Cost</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @travel_maps.each do |travel_map| %>
      <tr>
        <td><%= travel_map.name %></td>
        <td><%= travel_map.description %></td>
        <td><%= travel_map.duration %></td>
        <td><%= travel_map.cost %></td>
        <td><%= travel_map.profile %></td>
        <td><%= link_to 'Show', travel_map %></td>
        <td><%= link_to 'Edit', edit_travel_map_path(travel_map) %></td>
        <td><%= link_to 'Destroy', travel_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Travel map', new_travel_map_path %>

app/views/travel_maps/new.html.erb
<h1>New Travel Map</h1>

<%= render 'form' %>

<%= link_to 'Back', travel_maps_path %>

app/views/travel_maps/show.html.erb
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeNWRjNW5DRK6MLdNA1HkxhpsqZVlmCY8&callback=initMap">
    </script>

    <%= javascript_include_tag "travel_maps.js" %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h1 class=" text-center">
          <%= @travel_map.name %>
        </h1>
      </div>
      <div class="panel-body">
        <div class="col-md-7">
<!--           <div style='width: 800px;'> -->
            <div id="map" style='width: 100%; height: 400px;'>
              <script type="text/javascript">
                  customStyle = [{"featureType":"administrative","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType": "administrative","elementType": "geometry.fill", "stylers": [{ "visibility": "off" }]},{"featureType":"administrative.locality","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"administrative.neighborhood","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"landscape.man_made","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"landscape.natural","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"poi","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}];
                  handler = Gmaps.build('Google');
                  handler.buildMap({ 
                    provider: {
                      zoom: 1,
                      center: new google.maps.LatLng(0, 0),
                      streetViewControl: false,
                      mapTypeControl: false,
                      styles: customStyle
                    }, 
                  internal: {id: 'map'}}, 
                  function(){
                    markers = handler.addMarkers(
                      <%=raw @hash.to_json %>
                      // [
                      // {
                        // "lat": 48.8,
                        // "lng": 2.3,
                    //     "picture": {
                    //       "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
                    //       "width":  32,
                    //       "height": 32
                    //     },
                    //     "infowindow": "hello!"
                      // }
                    // ]
                    );

                    <% if @hash.size > 1 %>
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                    <% end %>
                  });
              </script>
            <!-- </div> -->
          </div>

          <br>
          <%= link_to 'Add a new destination', new_location_path(travel_map: @travel_map), class: "btn btn-default" %>
        </div>

        
        <div class="col-md-5">

          <% if not current_user == @travel_map.profile.user %>
            <div>
            <%= fa_icon "user 3x" %>
            <h3>
              <%= @travel_map.profile.first_name %>
            </h3>
            </div>
          <% end %>


          <p>
            <strong>Description:</strong>
            <%= @travel_map.description %>
          </p>

          <p>
            <strong>Duration:</strong>
            <%= @travel_map.duration %>
          </p>

          <p>
            <strong>Cost:</strong>
            <%= @travel_map.cost %>
          </p>
      
          <%= link_to 'Edit map details', edit_travel_map_path(@travel_map) %>
          
          <%= @testvariable %>
          
 
        </div>

      </div>
    </div>
  </div>
</div>

<div class="row">
  <h2 class="text-center">Locations</h2>
</div>

<div clas="row">

          <% @locations.each do |location| %>
            <div class = "col-md-2">
              <div class = "panel panel-default">
                <div class = "panel-body">

                  <div class="row text-center">
                    <%= fa_icon "picture-o 3x" %>
                  </div>
                  <div class="row text-center">
                    <p><%= location.name %></p>
                  </div>

                  <div class="row text-center">
                    <%= link_to 'Remove', {:controller => "travel_maps", :action => "remove", :location => location.id}, method: "post", class: "btn btn-warning"%>

                  <!-- delete_location_from_map(location) -->
                  </div>

                  </div>
                </div>
              </div>
          <% end %>
</div>